name: sparsifier-model
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - faiss-gpu
  - pytorch
  - torchvision
  - pytorch-lightning
  - transformers
  - numpy<2
  - nltk
  - pip:
      - wandb
      - beir
