name: sparsifier-model
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - faiss-gpu
  - pytorch=2.6.0
  - torchvision=0.21.0
  - pytorch-lightning=2.5.1.post0
  - pillow=11.3.0
  - datasets=3.6.0
  - transformers
  - numpy<2
  - nltk
  - pip:
      - wandb
      - beir
