#!/bin/bash

# Initialize
pylucene_version=9.10.0
pylucene=pylucene-$pylucene_version
pylucene_file=${pylucene}-src.tar.gz
is_install_jvm=true

# Build
if [  -f "$pylucene_file" ] ; then
  echo "PyLucene file already downloaded"
else
  wget https://dlcdn.apache.org/lucene/pylucene/$pylucene_file
  tar xzf $pylucene_file
fi
if [ "$is_install_jvm" = true ] ; then
  if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo "Linux detected. Install temurin-17-jdk"
    apt -q install -y wget apt-transport-https gpg
    wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor | tee /etc/apt/trusted.gpg.d/adoptium.gpg > /dev/null
    echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list
    apt -q update # update if you haven't already
    apt -q install temurin-17-jdk
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Mac OS detected. Skip JVM installation."
  else
    echo "Unknown OS type: $OSTYPE. Skip JVM installation."
  fi
fi

cp ../inverted-index/src/main/java/ru/itmo/sparsifiermodel/query/FieldValueAsScoreQuery.java \
  $pylucene/lucene-java-$pylucene_version/lucene/extensions/src/java/org/apache/pylucene/queries/

cd $pylucene/jcc || exit
python3 setup.py build
python3 setup.py install
cd ..

export PYTHON_PATH=$(which python3)
export PREFIX_PYTHON=${PYTHON_PATH%/bin/python3}
export PYTHON=$PYTHON_PATH
export JCC="$PYTHON -m jcc.__main__ --shared --arch x86_64"
export NUM_FILES=4
make
make install
make test
